# Generated by Django 2.0.9 on 2019-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haberler',
            name='slug',
            field=models.SlugField(editable=False, max_length=160, unique=True),
        ),
    ]
