# Generated by Django 2.0.9 on 2019-05-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0002_auto_20190513_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haberler',
            name='slug',
        ),
    ]
